
libs = [ "opencv-ffi", "eigen", "opensurf" ]

task :default => libs

# Because this Rakefile is run in a pretty sanitized environment (see rubygems/ext/rake_builder.rb)
# chaining to another ruby is actually problematic...
libs.each { |l|
  task l do
    Dir.chdir( [File.dirname(__FILE__),l].join('/') )
    sh "bundle exec ruby 'mkrf_conf.rb'" unless File.exists?( 'Rakefile' )
    sh 'bundle exec rake build_library'
  end
}

